### ISSUE TITLE
Listen Cancel button Event

### ISSUE THREAD

**Issue by yigityuksel** [honkmaster/TTOpenInAppActivity#35]
hi,

Is there any way to listen cancel button in activitiy ?

**Comment by cekistezeytin** [comment]
I think, i found the solution.

` [self presentViewController:activityViewController animated:YES completion:NULL];
        
        activityViewController.completionWithItemsHandler = ^(NSString *activityType, BOOL completed, NSArray *returnedItems, NSError *activityError) {
            
            NSLog(@"completionWithItemsHandler, activityType: %@, completed: %d, returnedItems: %@, activityError: %@", activityType, completed, returnedItems, activityError);
        };`
